$axure.loadCurrentPage({
  "url":"首页社区ok.html",
  "generationDate":new Date(1496630797800.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2cc67fa1c0dd46709f6eafb3083afc15",
    "type":"Axure:Page",
    "name":"首页社区ok",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f887b104467948519b9e1ad3384e8116",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"7eae0193a65e431ca4eb8ac17758a1d2"},
{
          "id":"28b2cbea48fe470a832b351c80489dde",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":173,
              "y":84},
            "size":{
              "width":29,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页精选ok/u47_line.png"}},
{
          "id":"32c7390989a64d1799c7d7dd8bbe5a81",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":13,
              "y":109},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6696b082d48845d783feb96cb3284f09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":13,
                  "y":109},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"304e5e5444c2403ca588102fdeaa2fbd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":89},
            "size":{
              "width":358,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页社区ok/u26_line.png"}},
{
          "id":"04db3a412cc948db81f0b31472ff3d2b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":185},
            "size":{
              "width":375,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页社区ok/u27_line.png"}},
{
          "id":"ed49cf5035674790996e1c5c5dd97762",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":50,
              "y":109},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d6d117ace044d1195b9e8f7ebf8da6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":50,
                  "y":109},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd275dfc06af4db78617ff03062a63cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":13,
              "y":135},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92b15b7f50574abeb229e6edd694a29d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":13,
                  "y":135},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d3976f6bb7c48afaefe9e2becd8dce9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":50,
              "y":135},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd91678f11804199ad24613c44e04d7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":50,
                  "y":135},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05c71899ff9e47459a664f0a8f152dcb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":13,
              "y":161},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3c7f2bba859476faa55ddaac62d57d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":13,
                  "y":161},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efded231b95c451c9872d12d3b2c8079",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":50,
              "y":161},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c97b72ca26844c8fbee8673b40d9a872",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":50,
                  "y":161},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c10eece2dcc84e45ad245c2ff212d2e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":34,
              "y":23},
            "size":{
              "width":320,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"31"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"295518b170cb4f9cb67d3d3870c20c2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":34,
                  "y":23},
                "size":{
                  "width":320,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"31"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页精选ok/u35.png"}},
{
          "id":"7f51fb6c441a49dd8b66438ec0cfdbfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":176,
              "y":29},
            "size":{
              "width":25,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed46609d050f43909ab3347fbe101ce8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":176,
                  "y":29},
                "size":{
                  "width":25,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a39bfb53c25416c9069123d76e39f1b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "opacity":"0.5",
            "location":{
              "x":43,
              "y":29},
            "size":{
              "width":16,
              "height":16},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e0bcf9f73ef4494ba39db9aac9f0a17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "opacity":"0.5",
                "location":{
                  "x":43,
                  "y":29},
                "size":{
                  "width":16,
                  "height":16},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页精选ok/u45.png"}},
{
          "id":"4906f571aa3440d1a6db2174d0cc3b31",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":49},
            "size":{
              "width":373,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页精选ok/u73_line.png"}},
{
          "id":"484446ade3ce4f3cbf59d05a346f4657",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "lineSpacing":"19px",
            "location":{
              "x":12,
              "y":262},
            "size":{
              "width":350,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd95a8dcc79e441dbbeeb297dab4504a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "lineSpacing":"19px",
                "location":{
                  "x":12,
                  "y":262},
                "size":{
                  "width":350,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"047a8e9952af4c8dbe54810b2d14d9c9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":320},
            "size":{
              "width":350,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页精选ok/u52_line.png"}},
{
          "id":"927be162b7b8463e971047138beb440b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":12,
              "y":232},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b028c3d5eec54cc59f7ff9d42cd3cc7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":12,
                  "y":232},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页精选ok/u53.png"}},
{
          "id":"716e8e9b0dfc4d53bca8d83f9609b52f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":36,
              "y":235},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dbb63b053d74e1ca02101cb75330cc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":235},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e2f5a36bb614ac4a03f7dd6151d6f83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":317,
              "y":305},
            "size":{
              "width":45,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a4b5e3a29d14335b9fc27d41bef27de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":317,
                  "y":305},
                "size":{
                  "width":45,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee3f9fe817fb4f3d9e40eb49d01b8233",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "lineSpacing":"19px",
            "location":{
              "x":14,
              "y":598},
            "size":{
              "width":350,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3cab7c28bab4a86b2926be6b3ea675c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "lineSpacing":"19px",
                "location":{
                  "x":14,
                  "y":598},
                "size":{
                  "width":350,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fa2f149004f4eb8adf97beabd966f00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":15,
              "y":580},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"507645a4ba1e4a95be0d0f31698f7a7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":15,
                  "y":580},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6829b29310d24dd789713e639d0d1c22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":95,
              "y":304},
            "size":{
              "width":22,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61f3693e6531478e8b9474d324015ae4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":95,
                  "y":304},
                "size":{
                  "width":22,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"498f32b4b3a740978d5f064b66c5354e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":34,
              "y":304},
            "size":{
              "width":28,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57b3b41ba0a04144ae1d06853be19717",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":304},
                "size":{
                  "width":28,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba40cca71fd549cf8c9f1a6a21f02676",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "opacity":"0.4",
            "location":{
              "x":72,
              "y":304},
            "size":{
              "width":18,
              "height":17},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf525143b0bb4e4f99b81aedfdda2eda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "opacity":"0.4",
                "location":{
                  "x":72,
                  "y":304},
                "size":{
                  "width":18,
                  "height":17},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页精选ok/u69.png"}},
{
          "id":"f27c392cfc9249efbedd08fc19006900",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "opacity":"0.5",
            "location":{
              "x":12,
              "y":300},
            "size":{
              "width":19,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14d8724f68f24af0b1c0926136473013",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "opacity":"0.5",
                "location":{
                  "x":12,
                  "y":300},
                "size":{
                  "width":19,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页精选ok/u71.png"}},
{
          "id":"c2ddf608db984bd8aaec311fbb9245ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":127,
              "y":304},
            "size":{
              "width":1,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62fa46e2015842df9de3fb1723b0d891",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":127,
                  "y":304},
                "size":{
                  "width":1,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91b0e2193eb549a6aa3138f112316782",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":219},
            "size":{
              "width":358,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页社区ok/u26_line.png"}},
{
          "id":"b2641d511a5e4a53950cc1eeab09eafa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":124,
              "y":304},
            "size":{
              "width":44,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5616767f72242919fec7d5c91966a09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":124,
                  "y":304},
                "size":{
                  "width":44,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1b726b76dac47b6b8a48bc66145ac29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":45,
              "y":66},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34911f1eb5ec4984bc769cb6e76b568b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":45,
                  "y":66},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b781f76486f94cddbd48a3e21296bd88",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":296,
              "y":66},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1931842930a34298a0ca36c10f8db7d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":296,
                  "y":66},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0146f6fbcc994accbfe9e777570273ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":173,
              "y":66},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3815f89a839e47029ce7d8c18b38df91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":173,
                  "y":66},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25c6872094a04044adb293955ca7585e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":107,
              "y":69},
            "size":{
              "width":17,
              "height":10},
            "rotation":"90",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页精选ok/u48_line.png"}},
{
          "id":"f3f9c52edaaf4304b1b4add4578ed5e2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":69},
            "size":{
              "width":17,
              "height":10},
            "rotation":"90",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页精选ok/u48_line.png"}},
{
          "id":"c3dd661cfc8b4b90a90327ccf6dbe801",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "lineSpacing":"19px",
            "location":{
              "x":12,
              "y":360},
            "size":{
              "width":290,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f8dd7482ca0418aabf4667e72172bcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "lineSpacing":"19px",
                "location":{
                  "x":12,
                  "y":360},
                "size":{
                  "width":290,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0cbf2c5f59994e2e99c0cd1d080dfb39",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":560},
            "size":{
              "width":350,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页精选ok/u52_line.png"}},
{
          "id":"a1781208e17849378c728209a6164fc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":12,
              "y":330},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d1dba1d1774471397bd99c089cb8b11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":12,
                  "y":330},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页精选ok/u53.png"}},
{
          "id":"ee38f557237c44b085238b3c854370da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":36,
              "y":334},
            "size":{
              "width":49,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cda80aad6cf449f489bdc6b945e7b146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":334},
                "size":{
                  "width":49,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4105d32c864f4c9cb286cd3720c5d818",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":299,
              "y":537},
            "size":{
              "width":51,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6776419cfe54b5e80f947a073f80fcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":299,
                  "y":537},
                "size":{
                  "width":51,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e8878a66638498fb2534faad7a02e0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFCFCFC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF0F0F0},
            "location":{
              "x":34,
              "y":390},
            "size":{
              "width":307,
              "height":130},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0235135710fc48168e211389f80ae6c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0F0F0},
                "location":{
                  "x":34,
                  "y":390},
                "size":{
                  "width":307,
                  "height":130},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页精选ok/u89.png"}},
{
          "id":"99e32eee5df64e1d8a1bcf82c7e7ad2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":95,
              "y":536},
            "size":{
              "width":19,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"478ee86b87c747228463d490391a53f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":95,
                  "y":536},
                "size":{
                  "width":19,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6ce0e47ab234938b5f1353c34c06aed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":34,
              "y":536},
            "size":{
              "width":24,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"714c4a8f13e6421d9bda157f6d09047e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":536},
                "size":{
                  "width":24,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f47695377551476f8758900c5b007f5a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "opacity":"0.4",
            "location":{
              "x":72,
              "y":536},
            "size":{
              "width":18,
              "height":17},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"017037df365e45c8884085cb3c22170c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "opacity":"0.4",
                "location":{
                  "x":72,
                  "y":536},
                "size":{
                  "width":18,
                  "height":17},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页精选ok/u69.png"}},
{
          "id":"324cc58cc7c74a11b08e21c63453b99e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "opacity":"0.5",
            "location":{
              "x":12,
              "y":532},
            "size":{
              "width":19,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51d099dc6a7a449c83a010eafa14999d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "opacity":"0.5",
                "location":{
                  "x":12,
                  "y":532},
                "size":{
                  "width":19,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页精选ok/u71.png"}},
{
          "id":"195827b7122646ba897dc180a185c9c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":127,
              "y":536},
            "size":{
              "width":1,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e5a298dbf7f45dbabd96aa205b58780",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":127,
                  "y":536},
                "size":{
                  "width":1,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26c639a083d240c8af8efcd46b300ff5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":127,
              "y":536},
            "size":{
              "width":44,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eadb56b4a3e7406fbc6d9f671911c385",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":127,
                  "y":536},
                "size":{
                  "width":44,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c55fd80250e4b53ac6ea64b93cde012",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":173,
              "y":444},
            "size":{
              "width":17,
              "height":23},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af578039d03742bcbce2532f1c113cae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":173,
                  "y":444},
                "size":{
                  "width":17,
                  "height":23},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页精选ok/u103.png"}},
{
          "id":"45321fb521a54e528f39933089637e80",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":181,
              "y":536},
            "size":{
              "width":27,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27a53cf4ad22417782996acfee3f7eba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":181,
                  "y":536},
                "size":{
                  "width":27,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页精选ok/u105.png"}},
{
          "id":"0f05417434464c9f93f5346066f96a7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":312,
              "y":548},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"570dab19cc3941c682a2b7a74f1d96cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":312,
                  "y":548},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页社区ok/u106.png"}},
{
          "id":"28ad6cf01da5475ba5107276799c2ebb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":324,
              "y":560},
            "size":{
              "width":26,
              "height":26},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f91cf1184d743c89b12de249909ffa9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":324,
                  "y":560},
                "size":{
                  "width":26,
                  "height":26},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页社区ok/u108.png"}},
{
          "id":"7899b9f7fb6a4916976091aefc8ac385",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":312,
              "y":548},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"22a8d75966cc420eaca0283da74e4fbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":16,
              "y":194},
            "size":{
              "width":84,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42f60832f0f340379683c57b0a454bb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":16,
                  "y":194},
                "size":{
                  "width":84,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页社区ok/u111.png"}},
{
          "id":"b2de208f754c4c66be794a470054a7c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":15,
              "y":678},
            "size":{
              "width":239,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d96fa230d1c9494ca9dd2f4ddcc09bcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":15,
                  "y":678},
                "size":{
                  "width":239,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"395022717ada4de2931acde41e9b483c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":15,
              "y":752},
            "size":{
              "width":27,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46650c48f39845b4976d1a1dfc593e8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":15,
                  "y":752},
                "size":{
                  "width":27,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页精选ok/u105.png"}},
{
          "id":"499f691d0954475e8c7b86678ceeed0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":55,
              "y":752},
            "size":{
              "width":49,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cac7e983e6c442ca421d632e230103e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":55,
                  "y":752},
                "size":{
                  "width":49,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页精选ok/u111.png"}},
{
          "id":"df30ba63ec9a4afc94a4a328a3e28eaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":110,
              "y":200},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac0abc9b87b94269aaf6645e87df138a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":110,
                  "y":200},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94bf77ea1b2f49228bbe862e923a6de5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":176,
              "y":200},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7e8bd9d0366453bad0854fcadfb0543",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":176,
                  "y":200},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cefe3e7182c46a7bc00230efc5e840e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":12,
              "y":790},
            "size":{
              "width":239,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd7f8b161d2c49848b3cd4ac7b9f9f42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":12,
                  "y":790},
                "size":{
                  "width":239,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "7eae0193a65e431ca4eb8ac17758a1d2":{
      "packageId":"7eae0193a65e431ca4eb8ac17758a1d2",
      "type":"Axure:Master",
      "name":"基础版",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"af226c488fc941e99484bd2cec4340b8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "size":{
                "width":375,
                "height":667},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8dd1e2ae969848c89b84fa587a460694",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "size":{
                    "width":375,
                    "height":667},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页精选ok/u1.png"}},
{
            "id":"7284e38442fc45348b8cd88281ff40b3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "size":{
                "width":375,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8616946ea493495780d9b0b3611246e1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "size":{
                    "width":375,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页精选ok/u3.png"}},
{
            "id":"d36da1d223a64946a9e94711eff4d1fd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"solid",
                "color":0xFFF6F6F6},
              "location":{
                "x":1,
                "y":623},
              "size":{
                "width":375,
                "height":44},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d16164721be54e25b197dd7f375e03e6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF6F6F6},
                  "location":{
                    "x":1,
                    "y":623},
                  "size":{
                    "width":375,
                    "height":44},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页精选ok/u5.png"}},
{
            "id":"315f60303f144000ae765c6d624bf077",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":29,
                "y":628},
              "size":{
                "width":22,
                "height":23},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b24b94422e9e4efb87aec6e5adef1e28",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":29,
                    "y":628},
                  "size":{
                    "width":22,
                    "height":23},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页精选ok/u7.png"}},
{
            "id":"31a4ebba4b024c0985313097bd4aa241",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "opacity":"0.5",
              "location":{
                "x":128,
                "y":628},
              "size":{
                "width":22,
                "height":21},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"acd0c3901d5d492eb40e111abba88684",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "opacity":"0.5",
                  "location":{
                    "x":128,
                    "y":628},
                  "size":{
                    "width":22,
                    "height":21},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页精选ok/u9.png"}},
{
            "id":"edba010e20634dc1ac330c3bf8d76748",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "opacity":"0.5",
              "location":{
                "x":325,
                "y":628},
              "size":{
                "width":22,
                "height":22},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a16f9a63e6624c72ae69bd642a87de50",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "opacity":"0.5",
                  "location":{
                    "x":325,
                    "y":628},
                  "size":{
                    "width":22,
                    "height":22},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页精选ok/u11.png"}},
{
            "id":"c7807a3a08ad4fed9a38119bc20c8755",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "opacity":"0.5",
              "location":{
                "x":226,
                "y":628},
              "size":{
                "width":22,
                "height":22},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c26cef48b2564499bc5c30f85331e754",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "opacity":"0.5",
                  "location":{
                    "x":226,
                    "y":628},
                  "size":{
                    "width":22,
                    "height":22},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页精选ok/u13.png"}},
{
            "id":"48809f0583444dcea10978992980261a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF868686,
                "opacity":1},
              "location":{
                "x":31,
                "y":652},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2378ba57c1274dd28ce75ae2102d4178",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF868686,
                    "opacity":1},
                  "location":{
                    "x":31,
                    "y":652},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5d3bac93c2934ccd9cdeaaf9db4428a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC,
                "opacity":1},
              "location":{
                "x":129,
                "y":652},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"314aac5cda1d4368ad98e59a8c422a75",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC,
                    "opacity":1},
                  "location":{
                    "x":129,
                    "y":652},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"262bd60e271747ee9a5adc99f7a3a2ef",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC,
                "opacity":1},
              "location":{
                "x":227,
                "y":652},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9a40c7bd14fe480ab352e3cea881e425",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC,
                    "opacity":1},
                  "location":{
                    "x":227,
                    "y":652},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"598eac4f5d6d41bba2fbab9208749178",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC,
                "opacity":1},
              "location":{
                "x":327,
                "y":652},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"99145e3a21ad4858a239c1698775eac9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC,
                    "opacity":1},
                  "location":{
                    "x":327,
                    "y":652},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "f887b104467948519b9e1ad3384e8116":{
      "scriptId":"u0",
      "af226c488fc941e99484bd2cec4340b8":{
        "scriptId":"u1"},
      "8dd1e2ae969848c89b84fa587a460694":{
        "scriptId":"u2"},
      "7284e38442fc45348b8cd88281ff40b3":{
        "scriptId":"u3"},
      "8616946ea493495780d9b0b3611246e1":{
        "scriptId":"u4"},
      "d36da1d223a64946a9e94711eff4d1fd":{
        "scriptId":"u5"},
      "d16164721be54e25b197dd7f375e03e6":{
        "scriptId":"u6"},
      "315f60303f144000ae765c6d624bf077":{
        "scriptId":"u7"},
      "b24b94422e9e4efb87aec6e5adef1e28":{
        "scriptId":"u8"},
      "31a4ebba4b024c0985313097bd4aa241":{
        "scriptId":"u9"},
      "acd0c3901d5d492eb40e111abba88684":{
        "scriptId":"u10"},
      "edba010e20634dc1ac330c3bf8d76748":{
        "scriptId":"u11"},
      "a16f9a63e6624c72ae69bd642a87de50":{
        "scriptId":"u12"},
      "c7807a3a08ad4fed9a38119bc20c8755":{
        "scriptId":"u13"},
      "c26cef48b2564499bc5c30f85331e754":{
        "scriptId":"u14"},
      "48809f0583444dcea10978992980261a":{
        "scriptId":"u15"},
      "2378ba57c1274dd28ce75ae2102d4178":{
        "scriptId":"u16"},
      "5d3bac93c2934ccd9cdeaaf9db4428a6":{
        "scriptId":"u17"},
      "314aac5cda1d4368ad98e59a8c422a75":{
        "scriptId":"u18"},
      "262bd60e271747ee9a5adc99f7a3a2ef":{
        "scriptId":"u19"},
      "9a40c7bd14fe480ab352e3cea881e425":{
        "scriptId":"u20"},
      "598eac4f5d6d41bba2fbab9208749178":{
        "scriptId":"u21"},
      "99145e3a21ad4858a239c1698775eac9":{
        "scriptId":"u22"}},
    "28b2cbea48fe470a832b351c80489dde":{
      "scriptId":"u23"},
    "32c7390989a64d1799c7d7dd8bbe5a81":{
      "scriptId":"u24"},
    "6696b082d48845d783feb96cb3284f09":{
      "scriptId":"u25"},
    "304e5e5444c2403ca588102fdeaa2fbd":{
      "scriptId":"u26"},
    "04db3a412cc948db81f0b31472ff3d2b":{
      "scriptId":"u27"},
    "ed49cf5035674790996e1c5c5dd97762":{
      "scriptId":"u28"},
    "2d6d117ace044d1195b9e8f7ebf8da6c":{
      "scriptId":"u29"},
    "fd275dfc06af4db78617ff03062a63cb":{
      "scriptId":"u30"},
    "92b15b7f50574abeb229e6edd694a29d":{
      "scriptId":"u31"},
    "6d3976f6bb7c48afaefe9e2becd8dce9":{
      "scriptId":"u32"},
    "fd91678f11804199ad24613c44e04d7e":{
      "scriptId":"u33"},
    "05c71899ff9e47459a664f0a8f152dcb":{
      "scriptId":"u34"},
    "d3c7f2bba859476faa55ddaac62d57d4":{
      "scriptId":"u35"},
    "efded231b95c451c9872d12d3b2c8079":{
      "scriptId":"u36"},
    "c97b72ca26844c8fbee8673b40d9a872":{
      "scriptId":"u37"},
    "c10eece2dcc84e45ad245c2ff212d2e9":{
      "scriptId":"u38"},
    "295518b170cb4f9cb67d3d3870c20c2f":{
      "scriptId":"u39"},
    "7f51fb6c441a49dd8b66438ec0cfdbfe":{
      "scriptId":"u40"},
    "ed46609d050f43909ab3347fbe101ce8":{
      "scriptId":"u41"},
    "8a39bfb53c25416c9069123d76e39f1b":{
      "scriptId":"u42"},
    "2e0bcf9f73ef4494ba39db9aac9f0a17":{
      "scriptId":"u43"},
    "4906f571aa3440d1a6db2174d0cc3b31":{
      "scriptId":"u44"},
    "484446ade3ce4f3cbf59d05a346f4657":{
      "scriptId":"u45"},
    "dd95a8dcc79e441dbbeeb297dab4504a":{
      "scriptId":"u46"},
    "047a8e9952af4c8dbe54810b2d14d9c9":{
      "scriptId":"u47"},
    "927be162b7b8463e971047138beb440b":{
      "scriptId":"u48"},
    "b028c3d5eec54cc59f7ff9d42cd3cc7b":{
      "scriptId":"u49"},
    "716e8e9b0dfc4d53bca8d83f9609b52f":{
      "scriptId":"u50"},
    "1dbb63b053d74e1ca02101cb75330cc0":{
      "scriptId":"u51"},
    "1e2f5a36bb614ac4a03f7dd6151d6f83":{
      "scriptId":"u52"},
    "1a4b5e3a29d14335b9fc27d41bef27de":{
      "scriptId":"u53"},
    "ee3f9fe817fb4f3d9e40eb49d01b8233":{
      "scriptId":"u54"},
    "b3cab7c28bab4a86b2926be6b3ea675c":{
      "scriptId":"u55"},
    "8fa2f149004f4eb8adf97beabd966f00":{
      "scriptId":"u56"},
    "507645a4ba1e4a95be0d0f31698f7a7c":{
      "scriptId":"u57"},
    "6829b29310d24dd789713e639d0d1c22":{
      "scriptId":"u58"},
    "61f3693e6531478e8b9474d324015ae4":{
      "scriptId":"u59"},
    "498f32b4b3a740978d5f064b66c5354e":{
      "scriptId":"u60"},
    "57b3b41ba0a04144ae1d06853be19717":{
      "scriptId":"u61"},
    "ba40cca71fd549cf8c9f1a6a21f02676":{
      "scriptId":"u62"},
    "cf525143b0bb4e4f99b81aedfdda2eda":{
      "scriptId":"u63"},
    "f27c392cfc9249efbedd08fc19006900":{
      "scriptId":"u64"},
    "14d8724f68f24af0b1c0926136473013":{
      "scriptId":"u65"},
    "c2ddf608db984bd8aaec311fbb9245ec":{
      "scriptId":"u66"},
    "62fa46e2015842df9de3fb1723b0d891":{
      "scriptId":"u67"},
    "91b0e2193eb549a6aa3138f112316782":{
      "scriptId":"u68"},
    "b2641d511a5e4a53950cc1eeab09eafa":{
      "scriptId":"u69"},
    "e5616767f72242919fec7d5c91966a09":{
      "scriptId":"u70"},
    "d1b726b76dac47b6b8a48bc66145ac29":{
      "scriptId":"u71"},
    "34911f1eb5ec4984bc769cb6e76b568b":{
      "scriptId":"u72"},
    "b781f76486f94cddbd48a3e21296bd88":{
      "scriptId":"u73"},
    "1931842930a34298a0ca36c10f8db7d1":{
      "scriptId":"u74"},
    "0146f6fbcc994accbfe9e777570273ab":{
      "scriptId":"u75"},
    "3815f89a839e47029ce7d8c18b38df91":{
      "scriptId":"u76"},
    "25c6872094a04044adb293955ca7585e":{
      "scriptId":"u77"},
    "f3f9c52edaaf4304b1b4add4578ed5e2":{
      "scriptId":"u78"},
    "c3dd661cfc8b4b90a90327ccf6dbe801":{
      "scriptId":"u79"},
    "0f8dd7482ca0418aabf4667e72172bcb":{
      "scriptId":"u80"},
    "0cbf2c5f59994e2e99c0cd1d080dfb39":{
      "scriptId":"u81"},
    "a1781208e17849378c728209a6164fc1":{
      "scriptId":"u82"},
    "3d1dba1d1774471397bd99c089cb8b11":{
      "scriptId":"u83"},
    "ee38f557237c44b085238b3c854370da":{
      "scriptId":"u84"},
    "cda80aad6cf449f489bdc6b945e7b146":{
      "scriptId":"u85"},
    "4105d32c864f4c9cb286cd3720c5d818":{
      "scriptId":"u86"},
    "b6776419cfe54b5e80f947a073f80fcc":{
      "scriptId":"u87"},
    "3e8878a66638498fb2534faad7a02e0e":{
      "scriptId":"u88"},
    "0235135710fc48168e211389f80ae6c1":{
      "scriptId":"u89"},
    "99e32eee5df64e1d8a1bcf82c7e7ad2a":{
      "scriptId":"u90"},
    "478ee86b87c747228463d490391a53f2":{
      "scriptId":"u91"},
    "f6ce0e47ab234938b5f1353c34c06aed":{
      "scriptId":"u92"},
    "714c4a8f13e6421d9bda157f6d09047e":{
      "scriptId":"u93"},
    "f47695377551476f8758900c5b007f5a":{
      "scriptId":"u94"},
    "017037df365e45c8884085cb3c22170c":{
      "scriptId":"u95"},
    "324cc58cc7c74a11b08e21c63453b99e":{
      "scriptId":"u96"},
    "51d099dc6a7a449c83a010eafa14999d":{
      "scriptId":"u97"},
    "195827b7122646ba897dc180a185c9c1":{
      "scriptId":"u98"},
    "1e5a298dbf7f45dbabd96aa205b58780":{
      "scriptId":"u99"},
    "26c639a083d240c8af8efcd46b300ff5":{
      "scriptId":"u100"},
    "eadb56b4a3e7406fbc6d9f671911c385":{
      "scriptId":"u101"},
    "1c55fd80250e4b53ac6ea64b93cde012":{
      "scriptId":"u102"},
    "af578039d03742bcbce2532f1c113cae":{
      "scriptId":"u103"},
    "45321fb521a54e528f39933089637e80":{
      "scriptId":"u104"},
    "27a53cf4ad22417782996acfee3f7eba":{
      "scriptId":"u105"},
    "0f05417434464c9f93f5346066f96a7b":{
      "scriptId":"u106"},
    "570dab19cc3941c682a2b7a74f1d96cf":{
      "scriptId":"u107"},
    "28ad6cf01da5475ba5107276799c2ebb":{
      "scriptId":"u108"},
    "9f91cf1184d743c89b12de249909ffa9":{
      "scriptId":"u109"},
    "7899b9f7fb6a4916976091aefc8ac385":{
      "scriptId":"u110"},
    "22a8d75966cc420eaca0283da74e4fbe":{
      "scriptId":"u111"},
    "42f60832f0f340379683c57b0a454bb6":{
      "scriptId":"u112"},
    "b2de208f754c4c66be794a470054a7c4":{
      "scriptId":"u113"},
    "d96fa230d1c9494ca9dd2f4ddcc09bcc":{
      "scriptId":"u114"},
    "395022717ada4de2931acde41e9b483c":{
      "scriptId":"u115"},
    "46650c48f39845b4976d1a1dfc593e8d":{
      "scriptId":"u116"},
    "499f691d0954475e8c7b86678ceeed0d":{
      "scriptId":"u117"},
    "9cac7e983e6c442ca421d632e230103e":{
      "scriptId":"u118"},
    "df30ba63ec9a4afc94a4a328a3e28eaa":{
      "scriptId":"u119"},
    "ac0abc9b87b94269aaf6645e87df138a":{
      "scriptId":"u120"},
    "94bf77ea1b2f49228bbe862e923a6de5":{
      "scriptId":"u121"},
    "f7e8bd9d0366453bad0854fcadfb0543":{
      "scriptId":"u122"},
    "5cefe3e7182c46a7bc00230efc5e840e":{
      "scriptId":"u123"},
    "cd7f8b161d2c49848b3cd4ac7b9f9f42":{
      "scriptId":"u124"}}});