$axure.loadCurrentPage({
  "url":"选择图片或视频ok.html",
  "generationDate":new Date(1496731369954.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"abe04200f8e54cae9d685b01eb803c84",
    "type":"Axure:Page",
    "name":"选择图片或视频ok",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4b1ee2aa67a242738f3392ebbc2277e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":375,
              "height":677},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e7714248ec04d4ebf48393d6412740e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":375,
                  "height":677},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u0.png"}},
{
          "id":"ac44c15c6c3849039d2f0f7bb9f790dc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":375,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0762b5d51b704f61be655364a393e2a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":375,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页精选ok/u3.png"}},
{
          "id":"f57f491f42994f96a475405dfd8d3de8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":50},
            "size":{
              "width":373,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页精选ok/u73_line.png"}},
{
          "id":"f7fe118193da4e6fa5edf127a685af23",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":138,
              "y":70},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9560d52f0e784de1a720c2e42a9b8c26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":138,
                  "y":70},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"13aa556db1674575a91daf4687f40b69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":258,
              "y":70},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"333881717dc94091baaed2e2bc1977e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":258,
                  "y":70},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"31e90f19235e49c6beb9854e68586118",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":138,
              "y":190},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bf95e5fd7e14e5dad8071aff08c9014",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":138,
                  "y":190},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"9086bfd6320146499e8ff6768ec12244",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":258,
              "y":190},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c5fe16ba87849b29997a2b2ac8e7d2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":258,
                  "y":190},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"ffa543aa4d664c9c816301036a9721e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":138,
              "y":310},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae32c20737624161988a28cb56e82a95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":138,
                  "y":310},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"91a977383a9c402b962e3bd609878da9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":258,
              "y":310},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5caf04d37ba647e89d68dc1375ac160f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":258,
                  "y":310},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"745737d54d9e4696a6fd40a5eec78987",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":138,
              "y":430},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c46fb1eea3d743348c50c8ff40a6287f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":138,
                  "y":430},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"08a2db0801b142fea3eb3e966fb1f930",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":258,
              "y":430},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e13bd8d53854ee5bc56fca664fdf524",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":258,
                  "y":430},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"60597b68120846808f9cb7821d05dad3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":138,
              "y":550},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5abd6a192744416b6d6cad1625be71d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":138,
                  "y":550},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"c7855f4441a143b483f45423b0586d47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":258,
              "y":550},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"278eb2864f164e06b9740a71d189bf79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":258,
                  "y":550},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"697394c0e2284cc6b1f1fa2ed768c9f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":18,
              "y":190},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2562fda69b644476bb43ded03e2c217f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":18,
                  "y":190},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"2d79bafd3ba349578f46238b719e4b22",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":18,
              "y":310},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d21610dd8baf4c11aa206c67e84975e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":18,
                  "y":310},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"56dd4ebd16b5412fbc7449ed3de9a68e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":18,
              "y":430},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0d88245935e41e4924e0230a2245eed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":18,
                  "y":430},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"5528454db0b7442088d411303a931a28",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":18,
              "y":550},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49bfe9516e7d4c1db971a97a20db78c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":18,
                  "y":550},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"e6a5d81a7db1443491e79f03db4dc66f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":176,
              "y":29},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11f51603960141a29cf6cb77453f6c9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":176,
                  "y":29},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"596efa3b24944459af7ee65d80a9371e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":6,
              "y":30},
            "size":{
              "width":22,
              "height":22},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"713e0d0a10a94f6a837e5f8c33ce7ce4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":6,
                  "y":30},
                "size":{
                  "width":22,
                  "height":22},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/精选视频详情ok/u41.png"}},
{
          "id":"1224dab5ef6f456fa4359ad2c8ec7ee2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":18,
              "y":70},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcc4bd56aee04653a10be4472ceb97f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":18,
                  "y":70},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"3964d149d3b54bda9e38ac3c26a7032d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":910,
              "y":440},
            "size":{
              "width":190,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e2a628010fa49f492b3a7ca28966c2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":910,
                  "y":440},
                "size":{
                  "width":190,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u39.png"}},
{
          "id":"1e70782d803340d8a249481779a7442e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":935,
              "y":464},
            "size":{
              "width":148,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10663cddd77f4f7c8bc2a12c4d010b5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":935,
                  "y":464},
                "size":{
                  "width":148,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce79a26a8fa8468f8c803a31b2ef4f8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":503,
              "y":10},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e110867ab4f84b25b336c628a5c60ee4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":503,
                  "y":10},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"376e2b80da9244428fbb1a689dee0929",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":503,
              "y":150},
            "size":{
              "width":40,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13062e8bee5a45edbf93f24d71f68627",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":503,
                  "y":150},
                "size":{
                  "width":40,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发视频ok/u91.png"}},
{
          "id":"35c606de2c1b44f9898c23d1f4f5b7e4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":512,
              "y":159},
            "size":{
              "width":22,
              "height":22},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60ad88851e99474390f001419ba10274",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":512,
                  "y":159},
                "size":{
                  "width":22,
                  "height":22},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/精选视频详情ok/u41.png"}},
{
          "id":"9c3fd20783794e0c8cf6d00b8db9c48e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":503,
              "y":54},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e2ae48a65a942deb64236c94bde948d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":503,
                  "y":54},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f630677a54f4079a20e4bec9b841f73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":503,
              "y":70},
            "size":{
              "width":369,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d02d057a98a542d781f3443fcd786fa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":503,
                  "y":70},
                "size":{
                  "width":369,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7378b458ca494de9abcf4cde08567452",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":560,
              "y":165},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6466b7c417bc4befaa30a79aac405293",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":560,
                  "y":165},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8cbd691daeb4bf88ce26598e3992d01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":503,
              "y":96},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3eeeedc3c8e242568f6f55207df73555",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":503,
                  "y":96},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8088713589c43baadb7aa512bea9ea2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":503,
              "y":111},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1c62d2c8809491bac68c3b3ece42a84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":503,
                  "y":111},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fcf01eba93d442bb5f4a808cd2cee8f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":195},
            "size":{
              "width":540,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择图片或视频ok/u59_line.png"}},
{
          "id":"c3906964b7ba4e4cb5e1fd22cbc7e80b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":620,
              "y":250},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0104a187c9dc4ae5ae2f1b88e5d87500",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":620,
                  "y":250},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"5b4b2d67c8b04ad7abd50da237e5342f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":740,
              "y":250},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"995cd8dc4a3b41f79d8dac13bf8f8cc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":740,
                  "y":250},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"bb653d6f45cb48cf8205372e69af12b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":500,
              "y":250},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8166fbbf173842a395e4748dd97947c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":500,
                  "y":250},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"cf227946575848caa1505cb0a7410939",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":499,
              "y":364},
            "size":{
              "width":341,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b03556962fe41948cb60baa8bf7ef4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":499,
                  "y":364},
                "size":{
                  "width":341,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83298aebf86c4e64a1601369fc2333cb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":700},
            "size":{
              "width":540,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择图片或视频ok/u59_line.png"}},
{
          "id":"d769d307dd3649188a165a2e4972a93b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":495,
              "y":720},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c61d8159696f430499ac6c0afe2756c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":495,
                  "y":720},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c794e3aa697042378dfa49ef6f8b0838",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":495,
              "y":754},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ebef4de28614f4787d129721d409eb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":495,
                  "y":754},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33c74778f1e6435bbd063a2ec9057719",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":560,
              "y":720},
            "size":{
              "width":373,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e387eea3921c4bb7a984fa711d5c3fe1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":560,
                  "y":720},
                "size":{
                  "width":373,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0cd35194791a4d5abcafe59938ff0a45",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":560,
              "y":754},
            "size":{
              "width":230,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9811e01cd34d4d008240400656517339",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":560,
                  "y":754},
                "size":{
                  "width":230,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"059ca8bcf14e418e91d7308752e20e67",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":780},
            "size":{
              "width":540,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择图片或视频ok/u59_line.png"}},
{
          "id":"9d0929b06eb9476981473f7642aef90d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":137},
            "size":{
              "width":540,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/选择图片或视频ok/u59_line.png"}},
{
          "id":"de0cd36f083943c2ba8fe08c2cd5a43e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":40.5,
              "y":92.5},
            "size":{
              "width":55,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"539b24bf7a3f47b88c1bcf4807241a2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":40.5,
                  "y":92.5},
                "size":{
                  "width":55,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u79.png"}},
{
          "id":"7eb891a3ba264b66bd8f5e609a723101",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":320,
              "y":29},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cece4b7873045f28d7331b7ab589e4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":320,
                  "y":29},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b5c30c8d4b4439f97c36bbf8601a537",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":820,
              "y":250},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f2a5c2333364ee7bc6df654cc795664",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":820,
                  "y":250},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u83.png"}},
{
          "id":"f7e60b730b764447b2471fe20f0a373a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1030,
              "y":250},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d69e89033844b05bc32c9ee8059c5dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1030,
                  "y":250},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"6f4b3614545941e8b26c25535ff54543",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":1150,
              "y":250},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df736b59fea141e2a9478e2fe8eea449",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":1150,
                  "y":250},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"53da325545dc41ce9371376c890b6a24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":910,
              "y":250},
            "size":{
              "width":100,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"144d83ea4a5844ce9b320a36c39a14c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":910,
                  "y":250},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u5.png"}},
{
          "id":"83dea5ada6834f00a725676ce91df6e0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1107,
              "y":251},
            "size":{
              "width":23,
              "height":23},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e5bd278f9b241b9b8d3b157e8b95680",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1107,
                  "y":251},
                "size":{
                  "width":23,
                  "height":23},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u91.png"}},
{
          "id":"ed0f6d7ebe7e4f89b55a854832368720",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":580,
              "y":250},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e06b04b107f4c4897ff68a18a791f58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":580,
                  "y":250},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择图片或视频ok/u83.png"}},
{
          "id":"12b26a18c7954e1aa0a79bfe7d8ad310",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":910,
              "y":364},
            "size":{
              "width":340,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"994f31218e38418cacf6c6c8e3f96072",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":910,
                  "y":364},
                "size":{
                  "width":340,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4b1ee2aa67a242738f3392ebbc2277e5":{
      "scriptId":"u0"},
    "4e7714248ec04d4ebf48393d6412740e":{
      "scriptId":"u1"},
    "ac44c15c6c3849039d2f0f7bb9f790dc":{
      "scriptId":"u2"},
    "0762b5d51b704f61be655364a393e2a1":{
      "scriptId":"u3"},
    "f57f491f42994f96a475405dfd8d3de8":{
      "scriptId":"u4"},
    "f7fe118193da4e6fa5edf127a685af23":{
      "scriptId":"u5"},
    "9560d52f0e784de1a720c2e42a9b8c26":{
      "scriptId":"u6"},
    "13aa556db1674575a91daf4687f40b69":{
      "scriptId":"u7"},
    "333881717dc94091baaed2e2bc1977e5":{
      "scriptId":"u8"},
    "31e90f19235e49c6beb9854e68586118":{
      "scriptId":"u9"},
    "1bf95e5fd7e14e5dad8071aff08c9014":{
      "scriptId":"u10"},
    "9086bfd6320146499e8ff6768ec12244":{
      "scriptId":"u11"},
    "1c5fe16ba87849b29997a2b2ac8e7d2f":{
      "scriptId":"u12"},
    "ffa543aa4d664c9c816301036a9721e0":{
      "scriptId":"u13"},
    "ae32c20737624161988a28cb56e82a95":{
      "scriptId":"u14"},
    "91a977383a9c402b962e3bd609878da9":{
      "scriptId":"u15"},
    "5caf04d37ba647e89d68dc1375ac160f":{
      "scriptId":"u16"},
    "745737d54d9e4696a6fd40a5eec78987":{
      "scriptId":"u17"},
    "c46fb1eea3d743348c50c8ff40a6287f":{
      "scriptId":"u18"},
    "08a2db0801b142fea3eb3e966fb1f930":{
      "scriptId":"u19"},
    "1e13bd8d53854ee5bc56fca664fdf524":{
      "scriptId":"u20"},
    "60597b68120846808f9cb7821d05dad3":{
      "scriptId":"u21"},
    "c5abd6a192744416b6d6cad1625be71d":{
      "scriptId":"u22"},
    "c7855f4441a143b483f45423b0586d47":{
      "scriptId":"u23"},
    "278eb2864f164e06b9740a71d189bf79":{
      "scriptId":"u24"},
    "697394c0e2284cc6b1f1fa2ed768c9f7":{
      "scriptId":"u25"},
    "2562fda69b644476bb43ded03e2c217f":{
      "scriptId":"u26"},
    "2d79bafd3ba349578f46238b719e4b22":{
      "scriptId":"u27"},
    "d21610dd8baf4c11aa206c67e84975e2":{
      "scriptId":"u28"},
    "56dd4ebd16b5412fbc7449ed3de9a68e":{
      "scriptId":"u29"},
    "e0d88245935e41e4924e0230a2245eed":{
      "scriptId":"u30"},
    "5528454db0b7442088d411303a931a28":{
      "scriptId":"u31"},
    "49bfe9516e7d4c1db971a97a20db78c1":{
      "scriptId":"u32"},
    "e6a5d81a7db1443491e79f03db4dc66f":{
      "scriptId":"u33"},
    "11f51603960141a29cf6cb77453f6c9e":{
      "scriptId":"u34"},
    "596efa3b24944459af7ee65d80a9371e":{
      "scriptId":"u35"},
    "713e0d0a10a94f6a837e5f8c33ce7ce4":{
      "scriptId":"u36"},
    "1224dab5ef6f456fa4359ad2c8ec7ee2":{
      "scriptId":"u37"},
    "fcc4bd56aee04653a10be4472ceb97f1":{
      "scriptId":"u38"},
    "3964d149d3b54bda9e38ac3c26a7032d":{
      "scriptId":"u39"},
    "6e2a628010fa49f492b3a7ca28966c2d":{
      "scriptId":"u40"},
    "1e70782d803340d8a249481779a7442e":{
      "scriptId":"u41"},
    "10663cddd77f4f7c8bc2a12c4d010b5e":{
      "scriptId":"u42"},
    "ce79a26a8fa8468f8c803a31b2ef4f8d":{
      "scriptId":"u43"},
    "e110867ab4f84b25b336c628a5c60ee4":{
      "scriptId":"u44"},
    "376e2b80da9244428fbb1a689dee0929":{
      "scriptId":"u45"},
    "13062e8bee5a45edbf93f24d71f68627":{
      "scriptId":"u46"},
    "35c606de2c1b44f9898c23d1f4f5b7e4":{
      "scriptId":"u47"},
    "60ad88851e99474390f001419ba10274":{
      "scriptId":"u48"},
    "9c3fd20783794e0c8cf6d00b8db9c48e":{
      "scriptId":"u49"},
    "3e2ae48a65a942deb64236c94bde948d":{
      "scriptId":"u50"},
    "2f630677a54f4079a20e4bec9b841f73":{
      "scriptId":"u51"},
    "d02d057a98a542d781f3443fcd786fa4":{
      "scriptId":"u52"},
    "7378b458ca494de9abcf4cde08567452":{
      "scriptId":"u53"},
    "6466b7c417bc4befaa30a79aac405293":{
      "scriptId":"u54"},
    "a8cbd691daeb4bf88ce26598e3992d01":{
      "scriptId":"u55"},
    "3eeeedc3c8e242568f6f55207df73555":{
      "scriptId":"u56"},
    "e8088713589c43baadb7aa512bea9ea2":{
      "scriptId":"u57"},
    "f1c62d2c8809491bac68c3b3ece42a84":{
      "scriptId":"u58"},
    "7fcf01eba93d442bb5f4a808cd2cee8f":{
      "scriptId":"u59"},
    "c3906964b7ba4e4cb5e1fd22cbc7e80b":{
      "scriptId":"u60"},
    "0104a187c9dc4ae5ae2f1b88e5d87500":{
      "scriptId":"u61"},
    "5b4b2d67c8b04ad7abd50da237e5342f":{
      "scriptId":"u62"},
    "995cd8dc4a3b41f79d8dac13bf8f8cc4":{
      "scriptId":"u63"},
    "bb653d6f45cb48cf8205372e69af12b0":{
      "scriptId":"u64"},
    "8166fbbf173842a395e4748dd97947c5":{
      "scriptId":"u65"},
    "cf227946575848caa1505cb0a7410939":{
      "scriptId":"u66"},
    "5b03556962fe41948cb60baa8bf7ef4e":{
      "scriptId":"u67"},
    "83298aebf86c4e64a1601369fc2333cb":{
      "scriptId":"u68"},
    "d769d307dd3649188a165a2e4972a93b":{
      "scriptId":"u69"},
    "c61d8159696f430499ac6c0afe2756c9":{
      "scriptId":"u70"},
    "c794e3aa697042378dfa49ef6f8b0838":{
      "scriptId":"u71"},
    "8ebef4de28614f4787d129721d409eb7":{
      "scriptId":"u72"},
    "33c74778f1e6435bbd063a2ec9057719":{
      "scriptId":"u73"},
    "e387eea3921c4bb7a984fa711d5c3fe1":{
      "scriptId":"u74"},
    "0cd35194791a4d5abcafe59938ff0a45":{
      "scriptId":"u75"},
    "9811e01cd34d4d008240400656517339":{
      "scriptId":"u76"},
    "059ca8bcf14e418e91d7308752e20e67":{
      "scriptId":"u77"},
    "9d0929b06eb9476981473f7642aef90d":{
      "scriptId":"u78"},
    "de0cd36f083943c2ba8fe08c2cd5a43e":{
      "scriptId":"u79"},
    "539b24bf7a3f47b88c1bcf4807241a2b":{
      "scriptId":"u80"},
    "7eb891a3ba264b66bd8f5e609a723101":{
      "scriptId":"u81"},
    "6cece4b7873045f28d7331b7ab589e4c":{
      "scriptId":"u82"},
    "9b5c30c8d4b4439f97c36bbf8601a537":{
      "scriptId":"u83"},
    "2f2a5c2333364ee7bc6df654cc795664":{
      "scriptId":"u84"},
    "f7e60b730b764447b2471fe20f0a373a":{
      "scriptId":"u85"},
    "4d69e89033844b05bc32c9ee8059c5dd":{
      "scriptId":"u86"},
    "6f4b3614545941e8b26c25535ff54543":{
      "scriptId":"u87"},
    "df736b59fea141e2a9478e2fe8eea449":{
      "scriptId":"u88"},
    "53da325545dc41ce9371376c890b6a24":{
      "scriptId":"u89"},
    "144d83ea4a5844ce9b320a36c39a14c3":{
      "scriptId":"u90"},
    "83dea5ada6834f00a725676ce91df6e0":{
      "scriptId":"u91"},
    "3e5bd278f9b241b9b8d3b157e8b95680":{
      "scriptId":"u92"},
    "ed0f6d7ebe7e4f89b55a854832368720":{
      "scriptId":"u93"},
    "1e06b04b107f4c4897ff68a18a791f58":{
      "scriptId":"u94"},
    "12b26a18c7954e1aa0a79bfe7d8ad310":{
      "scriptId":"u95"},
    "994f31218e38418cacf6c6c8e3f96072":{
      "scriptId":"u96"}}});